### PR TITLE
thread cleanup

### PR DESCRIPTION
**Pull request by ballessay**
Some cleanup and fixes for crashes rooted in the different static QThreads.

TBH I think the WebServerThread should be removed and replaced by some kind of manager class which calls a generic non-blocking command executor class.

### CODE REVIEW

**Comment by hteso** [comment]
I agree with:

> TBH I think the WebServerThread should be removed and replaced by some kind of manager class which calls a generic non-blocking command executor class.

If you create an issue for that specific request I'll assign it ti the 1.1 milestone but accept any PR that makes it.

**Comment by ballessay** [comment]
Hi, after I had a quick glance at the code now, I'd like to help make it "suck" less. I'm not sure if I should create an issue for every single problem I found or if I should create just one 'Make the code suck less' issue and work on it.

Some things I found:
- memory leaks
- the initalization flow (multiple dialogs which create a MainWindow).. or what happens after a 'New' (spawn a new process, kill the current one) should be changed
- nearly everything 'has/operates on' a MainWindow
- a lot duplicated code (e. g. the member pointer to ui elements)
- ... and more

Sorry I don't use telegram, or any other new messenger for that matter, to discuss this but I could create a discussion issue or feel free to contact me by mail.

**Comment by trufae** [comment]
I'll setup the irc-telegram bridge soon so you can use the irc channel too

**Comment by ballessay** [comment]
@trufae that would be very nice :+1:

**Pull request merged**
