### PR TITLE
Refactor FunctionsWidget, new features and much more

### LINKED ISSUE #49: Change the way QTreeWidgets are used
Currently, in `MainWindow::updateFrames()`, all Tree Widgets in symbolsTreeWidget, relocsTreeWidget, etc. are cleared and filled with QTreeWidgetItems using the result from parsed strings as columns.

Then, when double clicking an item to seek to the address, the displayed string from one of the columns is used instead of some other representation of the data attached to the QTreeWidgetItem.

So this should be changed to either
1. Attach additional data to the QTreeWidgetItems by using [setData()](http://doc.qt.io/qt-5.6/qtreewidgetitem.html#setData) or subclassing it or...
2. Use [QTreeView](http://doc.qt.io/qt-5.6/qtreeview.html) with custom Item Models (probably more elegant), see http://doc.qt.io/qt-5.6/model-view-programming.html

In general, addresses should not be represented as strings if not needed.

In addition, filling the Tree Views of sub-widgets should ideally not be done from the MainWindow class, but in each widget class for its own purpose.

This will go hand in hand with #2

### LINKED ISSUE #110: Different background color for imports in functions windows
Imports should have a Different background color in functions windows

### LINKED ISSUE #111: Highlight current function in Function windows
Highlight current function in Function windows

### PR DESCRIPTION
**Pull request by thestr4ng3r**
QRCore:
- Added RVA typedef to ut64 as a general type for addresses from r2. Don't know if it is really necessary to use a typedef here since afaik r2 internally also uses ut64 hardcoded everywhere, but it still does not harm.
- Added structs such as `FunctionDescription` to hold information about things obtained from r2
- Replaced fetching of functions, imports, symbols, comments, relocs and strings using `QRCore::getList()` with dedicated methods such as `QRCore::getAllFunctions()` that return lists of the structs mentioned before and perform the fetch using json commands or directly from r2.

FunctionsWidget:
- Completely refactored filling the tree by using QTreeView + QAbstractItemModel instead of QTreeWidget. This was necessary to implement the following things in a "nice" way.
- Highlight current function, resolves #111 
- Display a small icon next to the function name if it is an import, resolves #110 
- Added quick filter bar

General:
- Removed MainWindow::current_address
- Added Cursor Address. This should essentially correspond to the current address of the text cursor in the dissassembly view. If it changes, the signal `MainWindow::cursorAddressChanged()` is emitted, so anything can react to it, like the FunctionsWidget highlighting the current function.
- Removed some explicit font sizes set in .ui files to have consistent fonts.

This also partially resolves #49.

### CODE REVIEW

**Comment by ballessay** [comment]
@thestr4ng3r Sorry I've just commited some fixes which seems to conflict with your changes. Can you rebase your changes onto the current master?

**Comment by thestr4ng3r** [comment]
Rebase had some issues, I just did a merge.

**Comment by hteso** [comment]
Looks like it works fine \o/ I just have a copule of request for improvements:

- Please remove the big margins of the widget so the design is consisten with the other docks. Then I'll take care of some small redesigns once merged :)
- Could you restore the tooltip font? If we change or not that should be discussed and, if agreed, applied to all the GUI.
- I'm not sure if the icon should be on it's own column instead of by the name. Better look and the option to sort the items by type (imports) would be a benefit. What do you think?

Thanks for the awesome work! Be ready to do the same for the other item list docks once we have this settled :P

**Comment by thestr4ng3r** [comment]
> - Please remove the big margins of the widget so the design is consisten with the other docks. Then I'll take care of some small redesigns once merged :)

Done, the margins just didn't show on my environment.

> - Could you restore the tooltip font? If we change or not that should be discussed and, if agreed, applied to all the GUI.

Thanks for reminding me, I experimented with the font and forgot to reset it.

**Comment by ballessay** [comment]
I've some requests for improvement, too:
- functionswidget.cpp:16-23: Gives Warnings because the init order isn't correct, should be like defined in the header (side note: I personally prefer to first call the base class constructor, then the members)
- functionswidget.cpp:330: `main` is already initialized the the constructors initializer list. (Maybe from the merge?)

- MemoryWidget::setFcnName():1585: `ok` is never initialized, but used in the `if` on line 1590. (found with cppcheck)

Remark:
Do you use qmake or cmake? If cmake and there were no warnings we should add the same compiler warning switches to the cmake build as qmake uses.

The speedup is on refresh is quite nice. :+1:

**Pull request merged**
