### PR TITLE
Update to QtWebEngine

### PR DESCRIPTION
**Pull request by d235j**
This works with cursory testing, but needs further testing. This enables compatibility with Qt 5.6 and later (tested against 5.8).

Please review https://github.com/hteso/iaito/compare/master...d235j:qtwebengine?expand=1#diff-7ded75fae819b7e43fe0efbb950ef124R69 before merging.

### CODE REVIEW

**Comment by trufae** [comment]
@hteso i think we should go for 5.8, there shuoldnt be much regressions. but i'll try first,

**Comment by xpahos** [comment]
I made the same changes, but without this:

`ui->graphWebView->page()->runJavaScript("document.body.style.overflow='hidden';");`

Looks like there is no other way to hide scroll bars. Works for me on a Mac OS X Sierra && Qt 5.8 from a brew.

**Comment by trufae** [comment]
the scrolling in 5.8 seems to be very bad, also the topbar appears in black which looks bad too

**Comment by thestr4ng3r** [comment]
Maybe we should have a branch for this, so others can experiment with it.

**Comment by trufae** [comment]
is there a way to merge this without breaking qt5.3 compatibility? maybe with some ifdefs depending on version of qt?

**Comment by hteso** [comment]
I kind of like the idea of a branch for porting to a newer QT version, whatever it is, and marge once is working without issues. Would keep the code cleaner than with "ifdefs", right?

**Comment by trufae** [comment]
yes it will be cleaner, but the merge will be a pain, see for example branches in r2. we have some that are taking more than 1 year to be merged.. because of the amount of work that it involves to review all regressions introduced by bad merging and changes

**Comment by hteso** [comment]
You know better so I trust you. In that case I would propose waiting until we release the 1.0 and then face the migration to a newer Qt version.

**Comment by trufae** [comment]
Works for me but graphs doesnt seem to work, and there are some visual glitches

**Comment by trufae** [comment]
i think branches use to be a pain to maintain and we all want to go for 5.8, so what about supporting both just with ifdefs, this will make clear the differences, and we shuold only care about 5.3 until the release

**Comment by radare** [comment]
pls resolve conflicts and use
```
#if QT_VERSION >= 0x050000
```
to wrap your code (well. change that 05 for 58 i guess that would be fine)

**Comment by xpahos** [comment]
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 0e0369e..4d8807f 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -11,8 +11,18 @@ set(CMAKE_INCLUDE_CURRENT_DIR ON)
 set(CMAKE_AUTOMOC ON)
 set(CMAKE_AUTOUIC ON)
 set(CMAKE_AUTORCC ON)
-find_package(Qt5 REQUIRED COMPONENTS Core Widgets Gui WebKit WebKitWidgets)

+set(QT_USE_MODULES Core Widgets Gui)
+find_package(Qt5 REQUIRED COMPONENTS ${QT_USE_MODULES})
+if (Qt5_VERSION_MINOR GREATER 7)
+    list(APPEND QT_USE_MODULES WebEngine WebEngineWidgets)
+    message("Using QT5 WebEngine instead WebKit")
+    add_definitions(-DUSE_WEBENGINE)
+    find_package(Qt5 REQUIRED COMPONENTS ${QT_USE_MODULES})
+else (Qt5_VERSION_MINOR GREATER 7)
+    list(APPEND QT_USE_MODULES WebKit WebKitWidgets)
+    find_package(Qt5 REQUIRED COMPONENTS ${QT_USE_MODULES})
+endif(Qt5_VERSION_MINOR GREATER 7)

 if(WIN32)
     # use radare2 libraries from submodule on windows
@@ -137,5 +147,5 @@ add_definitions("-DAPP_VERSION=\"${IAITO_VERSION_FULL}\"")


 add_executable(iaito ${UI_FILES} ${QRC_FILES} ${SOURCE_FILES} ${HEADER_FILES})
-qt5_use_modules(iaito Core Widgets Gui WebKit WebKitWidgets)
+qt5_use_modules(iaito ${QT_USE_MODULES})
 target_link_libraries(iaito ${RADARE2_LIBRARIES})

diff --git a/src/widgets/memwidget/memorywidget.cpp b/src/widgets/memwidget/memorywidget.cpp
index 0a38df4..01faf71 100644
--- a/src/widgets/memwidget/memorywidget.cpp
+++ b/src/widgets/memwidget/memorywidget.cpp
@@ -11,11 +11,17 @@
 #include <QScrollBar>
 #include <QClipboard>
 #include <QShortcut>
-#include <QWebFrame>
 #include <QMenu>
 #include <QFont>
 #include <QUrl>

+#if defined(USE_WEBENGINE)
+    #include <QWebEnginePage>
+#else
+    #include <QWebFrame>
+#endif
+
+
 MemoryWidget::MemoryWidget(MainWindow *main, QWidget *parent) :
     QDockWidget(parent),
     ui(new Ui::MemoryWidget)
@@ -66,9 +72,14 @@ MemoryWidget::MemoryWidget(MainWindow *main, QWidget *parent) :
     graph_bar->setVisible(false);

     // Hide graph webview scrollbars
+
+#if defined(USE_WEBENGINE)
+    ui->graphWebView->page()->runJavaScript("document.body.style.overflow='hidden';");
+#else
     ui->graphWebView->page()->mainFrame()->setScrollBarPolicy(Qt::Vertical, Qt::ScrollBarAlwaysOff);
     ui->graphWebView->page()->mainFrame()->setScrollBarPolicy(Qt::Horizontal, Qt::ScrollBarAlwaysOff);
     QWebSettings::globalSettings()->setAttribute(QWebSettings::DeveloperExtrasEnabled, true);
+#endif

     // Add margin to function name line edit
     ui->fcnNameEdit->setTextMargins(5, 0, 0, 0);

diff --git a/src/widgets/memwidget/memorywidget.h b/src/widgets/memwidget/memorywidget.h
index c95d889..41ee916 100644
--- a/src/widgets/memwidget/memorywidget.h
+++ b/src/widgets/memwidget/memorywidget.h
@@ -11,11 +11,16 @@
 #include <QDockWidget>
 #include <QTreeWidget>
 #include <QTabWidget>
-#include <QWebView>
 #include <QUrl>
 #include <QPlainTextEdit>
 #include <QMouseEvent>

+#if defined(USE_WEBENGINE)
+    #include <QWebEngineView>
+#else
+    #include <QWebView>
+#endif
+
 class MainWindow;

 namespace Ui {
@@ -39,8 +44,13 @@ public:
     QTreeWidget      *xrefToTreeWidget_2;
     QTreeWidget      *xreFromTreeWidget_2;
     QTabWidget       *memTabWidget;
+#if defined(USE_WEBENGINE)
+    QWebEngineView         *graphWebView;
+    QWebEngineView         *histoWebView;
+#else
     QWebView         *graphWebView;
     QWebView         *histoWebView;
+#endif

     Highlighter        *highlighter;
     Highlighter        *highlighter_5;
```

**Comment by xpahos** [comment]
I'm not familiar with UI files. Maybe someone knows about conditional rules for *.ui?

**Comment by radare** [comment]
what about commiting the change instead of pasting the diff?

**Comment by ballessay** [comment]
@xpahos AFAIK ui files are plain xml, so no conditionals. But can't you just switch/include the different ui files with a conditional (qmake (untested)):

```
lessThan(QT_MINOR_VERSION, 7): FORMS += webkit.ui ...
else: FORMS += webeninge.ui ...
```
Or in cmake with `list(APPEND FORMS` (I'm not really experienced with cmake, but a `if (Qt5_VERSION_MINOR GREATER 7)` seems to be already in your diff)

**Comment by xpahos** [comment]
@radare yes, of course I will commit changes when I solve UI files problem.

@ballessay I created a separate directory for qt 5.8, but make generates header files using ui files from repo. 

```
139 if (Qt5_VERSION_MINOR GREATER 7)
140     list(APPEND UI_FILES webengine/widgets/memwidget/memorywidget.ui
141         webengine/widgets/dashboard.ui)
142     message("Added")
143 else (Qt5_VERSION_MINOR GREATER 7)
144     list(APPEND UI_FILES widgets/memwidget/memorywidget.ui
145         widgets/dashboard.ui)
146 endif (Qt5_VERSION_MINOR GREATER 7)
```

**Comment by radare** [comment]
Cool

**Comment by ballessay** [comment]
@xpahos Sorry it's hard to help without seeing the complete file. I guess your `list(APPEND UI_FILES...` is after the `set`. Maybe use "printf debugging" and print the UI_FILES list and/or other variables like `message(STATUS "${UI_FILES}")` after your stuff.

**Comment by xpahos** [comment]
@ballessay as I understand from this CMake automoc/uic source code https://github.com/Kitware/CMake/blob/e66eec143c86cb36bc468b78583f689840156d99/Source/cmQtAutoGenerators.cxx#L1065, ui files should be in the same directory as headers and source code. So we need to have separate directories for a webengine and for a webkit or do not use automoc/uic in CMake.

**Comment by mrexodia** [comment]
@xpahos should we close this in favor of #92 ? Perhaps you could give your opinion there to see if there is any difference between the end result of your pr and theirs.

Obviously it's not great to have wasted your time, but we have to choose which one to merge at some point.

Also I resolved the conflicts in this PR please check if I did that correctly.

**Comment by mrexodia** [comment]
Thanks! I merged these changes in #123

**Pull request closed without merging**
