### PR TITLE
Add CMakeLists.txt as an alternative to using qmake.

### PR DESCRIPTION
**Pull request by thestr4ng3r**
This adds the possibility to build the program using CMake instead of qmake. The result should be essentially the same.
I have created a dedicated find module for radare2/libr, which is potentially more elegant and reliable than hard-coding paths like /usr/lib in the project file.

### CODE REVIEW

**Comment by mrexodia** [comment]
Does this work on Windows? What is the point of duplicating the config? When this is accepted contributors will have to test both and modify both the project files. Qmake allows you to generate for a lot of IDE's so this feels like a lot of duplication effort...

**Comment by xpahos** [comment]
@mrexodia, for example, CLion doesn't have qmake support. https://youtrack.jetbrains.com/issue/CPP-318

**Comment by mrexodia** [comment]
Okay so if this happens (and I don't think it should) CMake should fully
replace the Qt project files or @hteso has to agree to maintain the CMake
files...

**Comment by trufae** [comment]
I dont think cmake gives any benefit over qmake and most ppl will use qtcreator which also allows to build in a headless way.. so i dont see much goodies into maintaining several Build systems

**Comment by thestr4ng3r** [comment]
The thing with qmake is that, while it is convenient to use with Qt only, it's very limited when it comes to using any other external libraries. It requires to directly specify library and include directories, which is something that ideally should not be part of the actual project definition.

I actually was able to successfully compile iaito using @mrexodia's modifications for windows and CMake by essentially just adding the needed paths to CMAKE_PREFIX_PATH and the find module automatically detected the libraries.

As long as Iaito's dependencies are as simple as they currently are, I personally don't think it would be a big problem to have two possibilities for building it. It might be important though to make it explicit which one is the "officially supported" method.

By the way, Qt Creator supports CMake projects as well, so this makes the qmake project more or less obsolete anyway.

**Comment by trufae** [comment]
As long as theres people using it, maintaining it and testing it in travis it is ok for me to get it merged. Are you gonna do this? I dont think deps will change too much

**Comment by thestr4ng3r** [comment]
@trufae Yes, I am planning to contribute more to the project in the future and since I use CLion, this is the way I will build it, so I will also continue to update it if necessary.

**Comment by trufae** [comment]
Then lgtm

**Comment by hteso** [comment]
Now that we have Windows support it is mandatory to also support Windows with this change. Is that already working for that platform?

**Comment by thestr4ng3r** [comment]
Theoretically yes, but the user has to make CMAKE_PREFIX_PATH point to iaito_win32 and iaito_win32/radare2 when running cmake, so it can find the libraries. I already compiled it that way.
But I can also change it to give it some more hints on windows later today, so that will happen automatically.

**Comment by xpahos** [comment]
@thestr4ng3r maybe it will be better to add something like

```
if (WIN32)
  execute_process(COMMAND git submodule update --recursive --remote)
endif (WIN32)
```

and put windows specific files to git submodule?

**Comment by thestr4ng3r** [comment]
@xpahos I don't know if it's a good idea to call git from cmake.

That's what I did in a separate branch:
```
if(WIN32)
	set(IAITO_WIN32_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../iaito_win32")
	list(APPEND CMAKE_PREFIX_PATH "${IAITO_WIN32_DIR}" "${IAITO_WIN32_DIR}/radare2")
	list(APPEND CMAKE_LIBRARY_PATH "${IAITO_WIN32_DIR}/radare2/lib32")
endif()
```

It expects the submodule to be updated already, like Iaito.pro.
I will merge this later.

**Comment by thestr4ng3r** [comment]
Windows now works right away.

**Comment by mrexodia** [comment]
👍

**Comment by hteso** [comment]
Ok, I'll merge the PR, but I can't maintain this as I know nothing about CMake. Are you going to take care of maintaining this?

**Comment by thestr4ng3r** [comment]
Yes, I will since I will be using it myself a lot.

**Pull request merged**
