### PR TITLE
Code refactoring and refresh ability

### PR DESCRIPTION
**Pull request by ballessay**
This started out to implement #126 but got a little bit out of control.

- Refresh shortcut (QKeySequence::Refresh) for all visible docks
- New base class for DockWidgets, which makes it easier to call functions on all of them (setup/refresh/hide/show...)
- Fixes most compiler and cppcheck warnings
- Initialize members
- Cleanup headers
- Decoupling of implementation details
...

### CODE REVIEW

**Comment by ballessay** [comment]
still WIP

**Comment by hteso** [comment]
Feel free to merge yourself when you consider it ready :) Just test it thoroughly!

**Comment by hteso** [comment]
After this PR, the navigation bar is not populated with the flag names so can't be used to seek to other functions. Please review what is missing :) I'll also look.

**Comment by hteso** [comment]
The problem is in the file `flagswidget.cpp` as the lines filling the omnibar are commented: lines 80, 92, 97 and 102. I won't uncomment them as may be you wanted to perform the omnibar fill in another way, if not let me know and I can enable those lines again.

**Comment by ballessay** [comment]
@hteso  I'll look into it this evening. I have a hunch what the source of this problem is.

**Comment by hteso** [comment]
Good, thanks :)

**Comment by ballessay** [comment]
@hteso Thanks for the hint. You were right, I forgot the OmiBar initialization part after commenting it out. But there was another problem with the CommentsWidget.

Both are should be fixed with #148

**Pull request merged**
