### PR TITLE
Add ConsoleWidget

### LINKED ISSUE #104: Console history not working
arrow keys ignored and dropdown menu is empty

### PR DESCRIPTION
**Pull request by ballessay**
- Moved the existing console functionality to a separate widget for easier
extension
- Added basic compleation and command line history

Should fix #104

### CODE REVIEW

**Comment by hteso** [comment]
Works perfect, thanks! A question:

The button with the arrow pointing down should show the history of commands executed by the user, and it is not working. Should we remove it or create an issue and make it work?

Feel free to merge the PR, thanks :)

**Comment by ballessay** [comment]
@hteso Thanks, but the implementation is far from perfect. ;)

Regarding your question: What the button should do I got from the tooltip, but I couldn't get it to work like I wanted. So currently its checkState used to switch between full completion (radare_args + history) or history only. 
Maybe it would be better to just complete the radare_args and for the history use Key_Up|Key_Down like in a shell?

**Comment by hteso** [comment]
One comment/thought: If we allow the user to change radare2 configuration with `e` commands, Iaitō will fail as it expects specific outputs and formats for, for example, the disassembly.

The question is, should we limit the commands the user can run from the console? Example, don't allow the execution of some `e`commands.

**Comment by ballessay** [comment]
@hteso Good point, I wasn't aware of that.

Proposal:
I remove the unwanted commands from the completion and check the user input and ignore unwanted ones. Would this be ok? Do you know of more problematic commands?

**Comment by hteso** [comment]
Good for me regarding the list of unwanted commands; let's start with the `e` commands and then we will add more once we discover them :)

As for the completion, I like your proposal:

> just complete the radare_args and for the history use Key_Up|Key_Down like in a shell

Let's give it a try and see if it works fine or we leave it the way you have it now (just with a different icon for the button).

Thanks!

**Pull request merged**
