### PR TITLE
Workaround for Qt5.8 WebEngine

### PR DESCRIPTION
**Pull request by xpahos**
I rewrite https://github.com/hteso/iaito/pull/40 and created a separate pull request. It's looking so ugly, but I don't have any ideas how to do it better. 

Tested with qt5.8 on Mac OS X. It will be very helpful if someone tests it on Windows machine.

### CODE REVIEW

**Comment by hteso** [comment]
Should we close #40 and keep working with this?

**Comment by xpahos** [comment]
@hteso I think yes. #40 could not be merged without full migration to WebEngine.

**Comment by mrexodia** [comment]
We could also update to Qt 5.6 and don't bother with keeping compatibility with Qt versions that don't support this webkit.

If support is really needed we can create `IaitoWebEngine` that derives from the correct engine and provide all the `#ifdef` functionality in there to keep things nice.

**Comment by xpahos** [comment]
@mrexodia 
> After the release of Qt 5.2, we will focus most of our new development efforts on the new Qt Web Engine. So, if you want to have all the lastest and greatest HTML5 features available for your application or device, you should consider moving over to Qt WebEngine once we have a release that covers the API features you require.

http://blog.qt.io/blog/2013/09/12/introducing-the-qt-webengine/
Actually, I don't know is it a good idea to continue using WebKit as an engine. brew dropped webkit support for qt https://github.com/Homebrew/legacy-homebrew/pull/50234/files

**Comment by hteso** [comment]
After knowing that there are issues with Qt 5.8 in Iaitō, I would prefer trying first Qt 5.6 and, regarding webkit, it is ok for me trying to move to qwebengine. But both of them after we release the 1.0. What do you think?

**Comment by mrexodia** [comment]
I have updated the code to solve a merge conflict. @xpahos please check if I didn't make a mistake in https://github.com/hteso/iaito/pull/92/commits/7802eff85e9b511082c370249f50117423ccdac4

**Comment by xpahos** [comment]
@hteso I think It's a good idea. WebEngine is not the main problem at this moment. Actually, I'm thinking about protobuf as a protocol for communication between r2 and interface. HTML rendering is a painful and heavy process for a user interface. But all these things can be done after basic functionality. 

@mrexodia looks good. Thank you.

**Comment by XVilka** [comment]
Protobuf seems a bit slower than msgpack. And neovim using it successfully.
May be it?

**Comment by mrexodia** [comment]
I think the main problem is that the graph isn't native to be honest...

**Comment by radare** [comment]
Yep, thats one reason but if iaito scheduled all tasks in an async way just running the commands in serie in a thread and collecting the results when ready it should be enough to noy make the ui sloppy.

In addition, moving everything to r2pipe would let iaito work with remote instances or being crash proof because r2 will run in a separate instance.

I dont think we should draw the graph when disassembling. It is not always neessary and could be done in background

**Comment by mrexodia** [comment]
> In addition, moving everything to r2pipe would let iaito work with remote instances or being crash proof because r2 will run in a separate instance.

😄 If I were to run r2 with the Windows heap checker enabled the same issues would occur. Apart from that I agree 👍

**Comment by radare** [comment]
That helped us to find some issues already, but those issues would still happen if reproducible by using the commands instead of the api. And easier because r2 crashes will happen in a clean process not messed up with qt/c++ things

**Comment by mrexodia** [comment]
Sorry, I messed up here and merged this while it probably shouldn't have. The references in `ui` files are not updated to reflect the change. I created a new branch with these changes but it needs more testing with multiple Qt versions and also the `.pro` file needs to be updated to work with this.

**Pull request merged**
