### PR TITLE
Support osx in travis build

### PR DESCRIPTION
**Pull request by ballessay**
Try to support osx builds on travis.

- Add osx stuff to .travis.yml
- Put travis steps into separate scripts for better reuse and cleaner travis.yml

**NOTE**
Still WIP.
PR used as playground/sandbox for travis.

### CODE REVIEW

**Comment by ballessay** [comment]
First build output, highly likely not working: https://transfer.sh/MNxbb/iaito-git.b444d16.dmg

I'm not sure if using scripts is a very good idea but a huge travis.yml isn't very nice either. Any opinions?

**Comment by biappi** [comment]
hello!

i found this PR by chance today. i tried the build at https://transfer.sh/MNxbb/iaito-git.b444d16.dmg and it does not link properly on my system, because `QtWebEngineWidgets` links to libraries in the brew cellar.

it's weird because the rest of Qt frameworks seems to be OK

```
willy@Lenalee  ~$ /Volumes/iaito/iaito.app/Contents/MacOS/iaito 
dyld: Library not loaded: /usr/local/Cellar/qt/5.8.0_2/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Volumes/iaito/iaito.app/Contents/Frameworks/QtWebEngineWidgets.framework/Versions/5/QtWebEngineWidgets
  Reason: image not found
Abort trap: 6
willy@Lenalee  ~$
```

```
willy@Lenalee  ~$ otool -L /Volumes/iaito/iaito.app/Contents/Frameworks/QtWebEngineWidgets.framework/Versions/5/QtWebEngineWidgets
/Volumes/iaito/iaito.app/Contents/Frameworks/QtWebEngineWidgets.framework/Versions/5/QtWebEngineWidgets:
	@executable_path/../Frameworks/QtWebEngineWidgets.framework/Versions/5/QtWebEngineWidgets (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtQuick.framework/Versions/5/QtQuick (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.8.0, current version 5.8.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtQml.framework/Versions/5/QtQml (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtWebChannel.framework/Versions/5/QtWebChannel (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtPositioning.framework/Versions/5/QtPositioning (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.8.0, current version 5.8.0)
	/usr/local/Cellar/qt/5.8.0_2/lib/QtQuickWidgets.framework/Versions/5/QtQuickWidgets (compatibility version 5.8.0, current version 5.8.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
willy@Lenalee  ~$ 
```

Sorry to chime in without a patch, but I didn't look further yet. I decided to leave a message anyway, because this fault could be masked if people testing this binary are brew users.

**Comment by ballessay** [comment]
Thanks that you tested the dmg and for providing that output. I don't have a current osx device, so this helps a lot. But to be honest at the moment I'm not sure why this happens. At the end of the build the script just calls `macdeployqt`, which should handle this stuff.

Maybe related: https://bugreports.qt.io/browse/QTBUG-41611

Edit: Recommended `-exectuable` flag doesn't fix the problem.

**Comment by biappi** [comment]
what a rabbit hole.

i spent a bit of time trying to build iato on my machine, and after some hacking i got a build. i could not reproduce the issue on my machine, `macdeployqt` works as it should. i used a mac build of QtCreator from the qt.io website.

after a bit of googling, i found out that it might be an interaction problem between qt and the way `brew` (the packet manager used to provision the travis vm) links its libraries.

there are quite a few interesting comments in github issues, maybe it's interesting

https://github.com/Homebrew/homebrew-core/issues/3219#issuecomment-235711413
> It's worth noting: Homebrew does not support using our binaries for shipping your own apps and we strongly recommend building Qt (and all your dependencies) from source yourself if you're relying on them behaving in a certain way.

https://github.com/Homebrew/homebrew-core/issues/3219#issuecomment-301423852
suggests the patch isn't landed in `brew` packages yet

https://github.com/Homebrew/homebrew-core/issues/6161#issuecomment-256350693
has an old workaround to fix `brew`'s own `macdeployqt`

https://github.com/Homebrew/homebrew-core/issues/6161#issuecomment-256571836
has a script to install qt in travis using official qt distributions

hope this helps!

**Comment by ballessay** [comment]
Wow! Thanks for your investigation. I'm just not sure yet which workaround I prefer. Guess the script/download from qt.io solution has the advantage that it'll be still possible to generate the output dmg directly.

Will try it out tomorrow.

**Comment by muammar** [comment]
@biappi Thank you very much for this. I have tried https://github.com/iltommi/macdeployqtfix and it fixed my bundle. !!!!!

**Comment by biappi** [comment]
@ballessay for what is worth, i agree. as a user i would prefer having the official qt builds, and the homebrew maintaners' consensus seems to discurage this kind of use of their system.

it's a bit more maintenance, but it should be easier to debug a bash script than an entire package distribution

@muammar yay! thank you. it makes me happy =)

**Comment by ballessay** [comment]
Alright, build with the official Qt libs is working now (as in: it builds). QtWebEngineWidgets seems to be relocated. Can someone give feedback if the application can be started now?

https://transfer.sh/D3kJE/iaito-git.46b21b3.dmg

TODO:
Include the radare2/www stuff + set/modify `http.root` so the web server is able to start.

@biappi You can find the link to the build output if you expand the `curl --upload-file...` entry, e. g. https://travis-ci.org/hteso/iaito/jobs/234317508#L3620 . I know it's not very user friendly, but I guess travis only generates a download button if a `deploy` step is used.

**Comment by biappi** [comment]
i can confirm the dmg at https://transfer.sh/D3kJE/iaito-git.46b21b3.dmg works fine!

🎉

**Comment by Maijin** [comment]
Use github release :P

**Comment by ballessay** [comment]
@biappi Thanks for your help, again. :+1: 

@Maijin If there's a release... ;)

**Comment by Maijin** [comment]
Project can be configured for every commit that's why better than relying on transfer.sh. It doesn't need tags, releases will just end-up in the untagged see here for example: https://github.com/radareorg/radare2-sigs/releases ; 
Usage of transfer.sh, mega.co, rapidshare etc. Is prone to expired link on Forum/Twitter/etc. it's just going to piss people off. Also prone to fake link etc.

**Comment by mrexodia** [comment]
What's going on here?

**Comment by Maijin** [comment]
It has been discussed on Telegram normally they have all the elements.

**Comment by Lazza** [comment]
> Usage of transfer.sh, mega.co, rapidshare etc. Is prone to expired link on Forum/Twitter/etc

Indeed, the links have already expired. Given that Travis builds the DMG files it would be great if we could test them for every build.

**Comment by Maijin** [comment]
Told you. Can you please update as described on telegram @ballessay ?

**Comment by ballessay** [comment]
> Can you please update as described on telegram

I'd like to, but I don't use/have telegram so I don't know what's described there (and iaitotg isn't working anymore). Be that as it may, I asked for a github token which wasn't provided so I couldn't continue. Can somebody ( @Maijin ?) provide me with the relevant part of the telegram messages? My email address is visible on my github profile, thanks in advance.

**Comment by Maijin** [comment]
Well I show to @hteso how to generate tokens etc. so he probably have all of this on his end.
I'll try to find back some of conversation.

**Comment by xarkes** [comment]
ping @hteso

**Comment by Maijin** [comment]
image
image

**Comment by Maijin** [comment]
Done in Cutter, this PR can be closed

**Pull request closed without merging**
